# This is a basic workflow that is manually triggered

name: echo secret sample

on:
  workflow_dispatch:

env:
  HOGEHOGE: ${{secrets.HOGEHOGE_KEY}}


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: echo hoge
      run: echo "secret is ${{secrets.HOGEHOGE_KEY}}"
